### ISSUE TITLE
In `dashboardPage` documentation, footer and controlbar are not defined

### ISSUE THREAD

**Issue by metanoid** [gyang274/ygdashboard#1]
It's not clear to the user what form the `footer` and `controlbar` inputs should take, and there are no defaults.

**Comment by gyang274** [comment]
Updated `dashboardPage()`'s example to show what should be taken by `footer`and `controlbar`, namely, `dashboardFooter()` and `dashboardControlbar()`.

In current version, both `dashboardFooter()`and `dashboardControlbar()` take some none user-friendly HTML type input, and has a self-amusement default. I am working on structuring these two functions' inputs.
