### ISSUE TITLE
Loading values from uploaded files 

### ISSUE THREAD

**Issue by germayneng** [gyang274/ygdashboard#2]
Hi YG, 

Once again, thanks for your wonderful dashboard. Really love the awesome features. Good Job and keep it up! 

Anyway, i wish to do a dynamic value where the user uploads a csv file and a particular value will be extracted and output onto the dynamic valuebox. I tested the code on a blank new shiny and it works, However, with the ygdashboard package and format, the output doesnt seem to appear. 

In the Ui's tab code: 
```
uploaddatatab <- tabItem(tabName = "uploaddatatab",
                          h1("Data Import"),
                          fluidRow(
                            box(height = "200px",
                                  title = "Upload File",
                                  solidHeader = TRUE, status = "info",
                                  fileInput("dashboarduploadFile", "APAC overview file",
                                            accept = c("text/csv", ".csv")), helpText("Upload a CSV file containing these columns:... etc File size no more than 0.5MB ")),
                            box(width = 12, solidHeader = TRUE, status = "success", valueBoxOutput("uploaddatavaluebox") )
                                    )
                            )
```

server code for this output: 

```
output$uploaddatavaluebox <- renderValueBox({
    # input$file1 will be NULL initially. After the user selects
    # and uploads a file, it will be a data frame with 'name',
    # 'size', 'type', and 'datapath' columns. The 'datapath'
    # column will contain the local filenames where the data can
    # be found.
    
    inFile <- input$file1
    
    if (is.null(inFile))
      return(NULL)
    
    test.value.file <- read.csv(inFile$datapath, header = input$header,
             sep = input$sep, quote = input$quote)
    test.value <- test.value.file[3,1]
    
    valueBox(test.value, "testing", icon = icon("thumbs-up"), color = "olive")
  })
```

I suspect this may be the same reason the calendar is not showing up for the dashboard! 
Hope you can look through!

Regards
Germayne

**Comment by gyang274** [comment]
Hi, @germayneng 

Thank you very much for your suggestion. 

Any luck figuring out the reason and how to fix it?

Regards,
Guang

**Comment by germayneng** [comment]
@gyang274 For the above issue, i use the base code from [here](http://shiny.rstudio.com/gallery/upload-file.html) and it seems to work. 

As for the calendar issue, i am still currently exploring. Hope you update the dashboard too! Keep it up! 
Its a really good job! 

Regards
Germ

**Comment by gyang274** [comment]
@germayneng, ok, I see. Thank you very much for your appreciation. - Guang
