### ISSUE TITLE
Unable to disable control bar in Dashboard page

### ISSUE THREAD

**Issue by koushikbalaji1** [gyang274/ygdashboard#4]
Hi 
I am able to turn off the controlbar sidemenu by assigning NULL to control bar in dashboardPage
`controlbar = NULL`

However the wrench icon still appears on the **navbar**, Is there an option to remove it ? 

Also I see that you have been working on adding components to the control bar, Is there any updates on that ?

Appreciate your efforts

**Comment by gyang274** [comment]
Hi, @koushikbalaji1 

Could you provide an example along with a screenshot to show the wrench icon you would like to remove?

Thank you.

Best Regards,
gyang274
