### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by calendarbase** [gyang274/ygdashboard#5]
Hi,
this looks promising.

I tried to install your package like this:

sudo su - -c "R -e \"install.packages('ygdashboard', repos = 'https://github.com/gyang274/ygdashboard')\""

Did not work, so I tried this:

sudo su - -c "R -e \"install.packages('shinydashboard', repos = 'https://github.com/gyang274/ygdashboard')\""

But it did not work as expected.

So how do i nstall it?

**Comment by DivadNojnarg** [comment]
Have you tried that:
```
install.packages("devtools")
library(devtools)
install_github("gyang274/ygdashboard)
```

**Comment by calendarbase** [comment]
I have not tried that. A brief setup instruction in the README would be a good help.
Thanks for the suggestion.
